apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          # Placeholder image: the CI workflow will patch this with the actual image
          # during deployment using `kubectl set image`.
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: TokenConfigurations__Audience
              value: "https://sapateiro.lucasnramos.com/"
            - name: TokenConfigurations__Issuer
              value: "https://sapateiro.lucasnramos.com/"
            - name: TokenConfigurations__Secret
              value: "VGVzdGVzIGNvbSAuTkVUIDYsIEFTUC5ORVQgQ29yZSBlIEpXVA=="
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
